### ISSUE TITLE
Error: Cannot configure a schema with no rules

### ISSUE THREAD

**Issue by iceshou** [MiYogurt/nodejs-shizhan#11]
async signUp() {
    const { ctx } = this
    await ctx.verify('user.signup', 'body')
    const { user } = await ctx.service.user.signUp()
    const ok = await this.ctx.service.user.sendVerifyEmail(
      '激活邮箱',
      user,
      this.signUpTemplate.bind(this)
    )
    this.ok(ok)
  }

报错，
Error: Cannot configure a schema with no rules
    at Schema.define (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\async-validator\lib\index.js:46:13)
    at new Schema (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\async-validator\lib\index.js:34:8)
    at Object.[egg-y-validator:getValidator] (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\egg-y-validator\app\extend\context.js:135:23)
    at Object.verify (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\egg-y-validator\app\extend\context.js:141:44)
    at User.signUp (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\app\controller\user.js:37:15)
    at Object.callFn (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\egg-core\lib\utils\index.js:46:21)
    at Object.classControllerMiddleware (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\egg-core\lib\utils\index.js:46:21)
    at wrappedController (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\koa-router\lib\router.js:346:16
    at dispatch (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\koa-compose\index.js:42:32)
    at passportSession (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\egg-passport\lib\framework.js:59:12)
    at dispatch (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\koa-compose\index.js:42:32)
    at passportInitialize (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\egg-passport\lib\framework.js:36:12)
    at dispatch (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\koa-compose\index.js:42:32)
    at F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\egg-y-validator\app\middleware\validator.js:15:15
    at dispatch (F:\code\study\nodejs-shizhan\chapter3\5-6\miao\node_modules\koa-compose\index.js:42:32)

**Comment by MiYogurt** [comment]
这个报错是由于传递了错误的验证参数吧。`await ctx.verify('user.signup', 'body')` 确保 user.signup 验证规则存在
