### ISSUE TITLE
103页发起post请求后，yaml文件报错

### ISSUE THREAD

**Issue by Kerminate** [MiYogurt/nodejs-shizhan#9]
```
{ YAMLException: cannot resolve a node with !<tag:yaml.org,2002:js/function> explicit tag at line 15, column 5:
        function validator(ctx) {
        ^
    at generateError (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:171:9)
    at composeNode (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1393:9)
    at readBlockMapping (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockSequence (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:928:5)
    at composeNode (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1331:12)
    at readBlockMapping (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1569:19)
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/internal/_pipe.js:3:14
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/internal/_arity.js:10:19
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/cond.js:47:30
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/internal/_arity.js:10:19
    at R.tryCatch.path (/Users/kepeilin/Documents/web-projects/diao/node_modules/_egg-y-validator@1.1.7@egg-y-validator/app/extend/context.js:61:23)
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/tryCatch.js:33:20
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/internal/_arity.js:10:19
    at Array.forEach (<anonymous>)
    at Object.loadDocs (/Users/kepeilin/Documents/web-projects/diao/node_modules/_egg-y-validator@1.1.7@egg-y-validator/app/extend/context.js:70:11)
    at Object.get docs [as docs] (/Users/kepeilin/Documents/web-projects/diao/node_modules/_egg-y-validator@1.1.7@egg-y-validator/app/extend/context.js:75:17)
```

**Comment by MiYogurt** [comment]
yml 格式可能写的有问题吧，找下yml的格式。对比下，或者自己用 js 写。

**Comment by Kerminate** [comment]
```
username:
  required: true
  message: '请填写用户名'
password:
  - min: 6
    messgae: '密码不能小于6位'
  - required: true
    message: '请填写密码'
confirm_password:
  - required: true
    message: '请填写确认密码'
  - validator: !!js/function >
    function validator(ctx) {
      return async function (rule, value, callback, source, options) {
        if (ctx.request.body.password === value) {
          await callback();
        }
        callback([{ message:'密码与确认密码不匹配', field:'confirm_password' }])
      }
    }
email:
  type: 'email'
  required: true
  message: '用户邮箱有误'
code:
  - required: true
    message: '必须填写邀请码'
```

**Comment by Kerminate** [comment]
https://github.com/nodeca/js-yaml/issues/448
这是我在 yaml 上提的issue

**Comment by MiYogurt** [comment]
一直都是全功能的引入 https://github.com/MiYogurt/node-m-import/blob/9af3a3f9db9dee9e566dee6e2734a96182023a15/src/index.js#L8

**Comment by Kerminate** [comment]
找到问题了。。validator的函数没有缩进。

**Comment by MiYogurt** [comment]
这样的js 是可以正常工作的。

```
module.exports = {
    name: [
        {required: true},
        {
            validator: (ctx) => {
                return function (rule, value, callback, source, options) {
                    callback([{ field: 'name', message: '错误' }])
                }
            }
        }
    ]
}
```
